platform :osx, '10.9'
inhibit_all_warnings!

target 'xflowparser', :exclusive => true do
  pod "xflowparser", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "xflowparser", :path => "../"
  pod "Kiwi"
end
