platform :osx, '10.10'
inhibit_all_warnings!


target 'xflowparser', :exclusive => true do
  pod 'Mantle', '~> 1.5.1'
  pod "xflowparser", :path => "../"
end

target 'Tests', :exclusive => true do
  pod 'Mantle', '~> 1.5.1'
  pod "xflowparser", :path => "../"
end
